version: '3.9'

services:
  pgvector:
    image: ankane/pgvector:latest
    ports:
      - "6024:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=rag_db
    volumes:
      - rag_pg_data:/var/lib/postgresql/data

volumes:
  rag_pg_data:
